### ISSUE TITLE
itch app install not working

### ISSUE THREAD

**Issue by anark10n** [jukibom/FlyDangerous#172]
Not sure whether this is a problem with the app, or the game itself, but it doesn't install when i try installing it from the app. Trying to install through the app throws the following error:
```20:59:56.673 INFO Queuing install for https://jukibom.itch.io/fly-dangerous...
20:59:56.677 ERROR While queuing download: TypeError: Cannot read property 'build' of undefined
    at file:///usr/share/itch/dist/renderer/7.chunk.js:894:39
    at doAsync (file:///usr/share/itch/dist/renderer/9.chunk.js:914:5)
    at PlanInstall.onInstall (file:///usr/share/itch/dist/renderer/7.chunk.js:881:94)
    at Object.ba (file:///usr/share/itch/dist/renderer/renderer.bundle.js:18384:84)
    at ja (file:///usr/share/itch/dist/renderer/renderer.bundle.js:18384:238)
    at ka (file:///usr/share/itch/dist/renderer/renderer.bundle.js:18384:292)
    at oa (file:///usr/share/itch/dist/renderer/renderer.bundle.js:18385:72)
    at lc (file:///usr/share/itch/dist/renderer/renderer.bundle.js:18422:146)
    at jc (file:///usr/share/itch/dist/renderer/renderer.bundle.js:18421:255)
    at mc (file:///usr/share/itch/dist/renderer/renderer.bundle.js:18422:334)
```
On Arch 5.17.9-arch1-1, Openpox 3.

**Comment by jukibom** [comment]
Honestly I didn't even know itch.io _had an app_ 😅

**Comment by jukibom** [comment]
@anark10n After a quick look around I apparently forgot to set the OS flags for the very latest build! Could you please try it now and let me know if that worked?

**Comment by anark10n** [comment]
yep, all fixed and installing correctly.
